apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/victorchu-dp/kargo-demo
      revision: main
      directories:
      - path: stages/*
  template:
    metadata:
      name: kargo-demo-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{path.basename}}
    spec:
      project: default
      source:
        repoURL: https://github.com/victorchu-dp/kargo-demo
        targetRevision: stage/{{path.basename}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-{{path.basename}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true